-- local Mason = {
--   'williamboman/mason.nvim',
--   cmd = { 'Mason' },
--   opts = {
--     ui = {
--       border = 'rounded',
--     },
--   },
-- }
--
-- local MasonToolInstaller = {
--   'WhoIsSethDaniel/mason-tool-installer.nvim',
--   dependencies = {
--     Mason,
--   },
--   cmd = { 'MasonToolsUpdate' },
--   opts = {
--     run_on_start = true,
--     auto_update = true,
--     ensure_installed = {
--       'stylua',
--       'prettierd',
--       'eslint_d',
--       'markdownlint',
--     },
--   },
--   keys = {
--     { '<leader>mtu', '<cmd>MasonToolsUpdate<CR>', desc = 'Mason Tool Update' },
--   },
-- }
--
-- local MasonLSPConfig = {
--   'williamboman/mason-lspconfig.nvim',
--   lazy = true,
--   dependencies = {
--     Mason,
--   },
--   opts = {
--     ensure_installed = {
--       'lua_ls',
--       'cssls',
--       'html',
--       'tsserver',
--       'bashls',
--       'jsonls',
--     },
--   },
-- }
--
-- return {
--   MasonToolInstaller,
--   MasonLSPConfig,
-- }
return {}
